# vim: set expandtab shiftwidth=2 tabstop=8 textwidth=0:

variables:
  FEDORA_RPMS: 'gcc gcc-c++ automake libtool make pkgconfig  python3 check-devel valgrind binutils doxygen xz'
  CENTOS_RPMS: $FEDORA_RPMS
  UBUNTU_DEBS: 'gcc g++     automake libtool make pkg-config python3 check       valgrind binutils doxygen xz-utils'
  DEBIAN_DEBS: $UBUNTU_DEBS
  LIBEVDEV_SKIP_ROOT_TESTS: 1

.default_artifacts: &default_artifacts
  artifacts:
    paths:
      - test/test-suite.log
    expire_in: 1 week
    when: on_failure

.default_build: &default_build
  script:
    - autoreconf -ivf
    - ./configure --disable-silent-rules
    - make
    - make check
  <<: *default_artifacts

.default_build_distcheck: &default_build_distcheck
  script:
    - autoreconf -ivf
    - ./configure --disable-silent-rules
    - make
    - make check
    - make distcheck
  <<: *default_artifacts

fedora:28:
  image: fedora:28
  before_script:
    - dnf upgrade -y
    - dnf install -y $FEDORA_RPMS
  <<: *default_build_distcheck

centos:7:
  image: centos:7
  before_script:
    - yum update -y
    - yum install -y $CENTOS_RPMS
  <<: *default_build_distcheck

ubuntu:18.04:
  image: ubuntu:18.04
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y $UBUNTU_DEBS
  <<: *default_build_distcheck

debian:stable:
  image: debian:stable
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y $DEBIAN_DEBS
  <<: *default_build_distcheck

# Build argument tests
#
# We run the build option combinations on the Centos image
# because it's the fastest one to yum update.
centos:7:no-valgrind:
  image: centos:7
  before_script:
    - yum update -y
    - yum install -y $CENTOS_RPMS
    - yum remove -y valgrind
  <<: *default_build_distcheck

centos:7:no-check:
  image: centos:7
  before_script:
    - yum update -y
    - yum install -y $CENTOS_RPMS
    - yum remove -y check check-devel
  <<: *default_build_distcheck

# doxygen is required for distcheck
centos:7:no-doxygen:
  image: centos:7
  before_script:
    - yum update -y
    - yum install -y $CENTOS_RPMS
    - yum remove -y doxygen
  <<: *default_build

# doxygen is required for distcheck
centos:7:no-doxygen-check-valgrind:
  image: centos:7
  before_script:
    - yum update -y
    - yum install -y $CENTOS_RPMS
    - yum remove -y doxygen valgrind check check-devel
  <<: *default_build

centos:7:no-nm:
  image: centos:7
  before_script:
    - yum update -y
    - yum install -y $CENTOS_RPMS
    - mv /usr/bin/nm /usr/bin/nm.moved
  <<: *default_build_distcheck

centos:7:enable-gcov:
  image: centos:7
  before_script:
    - yum update -y
    - yum install -y $CENTOS_RPMS
  script:
    - autoreconf -ivf
    - ./configure --disable-silent-rules --enable-gcov
    - make
    - make check
    - make distcheck
  <<: *default_artifacts
